### ISSUE TITLE
Desorden

### ISSUE THREAD

**Issue by martinjhm271** [UPPOSTCOOL/appcool#10]
tienen muchas ramas creadas,traten de unir todo su trabajo en 1 sola.

**Comment by kvncf** [comment]
Hola @martinjhm271 claro eso hacemos, mañana al momento de la entrega estará organizado en una sola gracias

**Comment by martinjhm271** [comment]
Hola,podrías hacerlo ahora? necesito calificar lo que llevan realizado,envíamelo a mi correo.

**Comment by kvncf** [comment]
Uy! lamento decirte que me queda un poco difícil :( aún no es posible unir con una versión estable, puedes calificar lo del master porque me da pena contigo mi hermano, un abrazo!
